### ISSUE TITLE
Need some examples of good visualizations that we can try to reproduce. 

### ISSUE THREAD

**Issue by MMenninger** [CMAP-REPOS/CMAP-R-Cookbook#5]

**Comment by MMenninger** [comment]
Can I paste an image?

![image](https://user-images.githubusercontent.com/6894600/70642842-921cda00-1c05-11ea-8c1e-7a848ad2c4e8.png)

**Comment by MMenninger** [comment]
![image](https://user-images.githubusercontent.com/6894600/70642948-c1cbe200-1c05-11ea-9981-5e41bf85ab5e.png)

**Comment by MMenninger** [comment]
![image](https://user-images.githubusercontent.com/6894600/70643024-e58f2800-1c05-11ea-83f5-d9df34dd2990.png)

**Comment by MMenninger** [comment]
Recessions

![image](https://user-images.githubusercontent.com/6894600/70643131-18392080-1c06-11ea-8b4a-5794599493ca.png)

**Comment by MMenninger** [comment]
![image](https://user-images.githubusercontent.com/6894600/70643172-27b86980-1c06-11ea-9c09-49b963491d71.png)

**Comment by MMenninger** [comment]
![image](https://user-images.githubusercontent.com/6894600/70644054-d9a46580-1c07-11ea-938a-4a68c5e82063.png)

**Comment by MMenninger** [comment]
![image](https://user-images.githubusercontent.com/6894600/70644103-efb22600-1c07-11ea-96f2-341c4f1045cb.png)

**Comment by tallishmatt** [comment]
@MMenninger I'm curious if you think shifting these images to a section of the wiki might be helpful, rather than recording them in an issue? Considering that they will serve as ongoing guidance as opposed to problems to solve.

**Comment by MMenninger** [comment]
Wiki started per @tallishmatt 
https://github.com/CMAP-REPOS/CMAP-R-Cookbook/wiki/Sample-images

**Comment by tallishmatt** [comment]
Link to wiki page now here:
https://github.com/CMAP-REPOS/CMAP-R-Cookbook/wiki/Example-Outputs
